version: '2'
services:
    jhipsterng2-app:
        image: jhipsterng2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterng2-postgresql:5432/jhipsterng2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterng2-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterng2-postgresql
